name: docker_local_development_CICD

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: api_gateway Build & Publish
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:/spring-boot-docker-local-development/api-gateway"
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/api-gateway:latest
      -
        name: discovery_service Build & Publish
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:/spring-boot-docker-local-development/discovery_service"
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/discovery_service:latest
